# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hHkwqKXr5sWai42q1bCdI6f7xHw9av3
"""

# ============================================================
# app.py - Flask Backend for Respiratory Disease Detection
# Project: ChestXrayProject
# ============================================================

import os
import numpy as np

from flask      import Flask, request, jsonify
from tensorflow import keras
from PIL        import Image

# ============================================================
# SECTION 1: App Configuration
# ============================================================

app = Flask(__name__)

# ---- Uploads folder -----------------------------------------
# ChestXrayProject/backend/uploads/
UPLOAD_FOLDER = os.path.join(os.path.dirname(__file__), 'uploads')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# ---- Allowed image formats ----------------------------------
ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'bmp'}

# ---- Image size (must match training) -----------------------
IMG_SIZE = (224, 224)

# ---- Class names in alphabetical order (must match training)-
# IMPORTANT: This order must match exactly what flow_from_directory
# assigned during training. It assigns labels alphabetically.
CLASS_NAMES = [
    'Bengin cases',       # index 0
    'Malignant cases',    # index 1
    'Normal cases',       # index 2
    'Pneumonia',          # index 3
    'Tuberclosis',        # index 4
    'covid'               # index 5
]

# ---- Friendly display names ---------------------------------
CLASS_DISPLAY_NAMES = {
    'Bengin cases'   : 'Benign Cancer',
    'Malignant cases': 'Malignant Cancer',
    'Normal cases'   : 'Normal',
    'Pneumonia'      : 'Pneumonia',
    'Tuberclosis'    : 'Tuberculosis',
    'covid'          : 'COVID-19'
}

# ============================================================
# SECTION 2: Load the Model
# ============================================================
# Model is loaded once when server starts.
# ChestXrayProject/model/best_model.h5

MODEL_PATH = os.path.join(
    os.path.dirname(__file__),   # ChestXrayProject/backend/
    '..',                         # go up to ChestXrayProject/
    'model',
    'best_model.h5'
)

print("Loading model... please wait.")

try:
    model = keras.models.load_model(MODEL_PATH)
    print(f"Model loaded successfully.")
    print(f"  Path          : {MODEL_PATH}")
    print(f"  Input shape   : {model.input_shape}")
    print(f"  Output shape  : {model.output_shape}")
except Exception as e:
    print(f"ERROR: Could not load model.")
    print(f"  Reason : {e}")
    print(f"  Fix    : Make sure best_model.h5 is inside ChestXrayProject/model/")
    model = None

# ============================================================
# SECTION 3: Helper Functions
# ============================================================

def allowed_file(filename):
    """
    Checks if uploaded file has a valid image extension.
    Returns True if allowed, False otherwise.
    """
    return (
        '.' in filename and
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
    )


def preprocess_image(image_path):
    """
    Prepares image for model prediction.
    Same steps used during training:
      1. Open image
      2. Convert to RGB
      3. Resize to 224x224
      4. Convert to numpy array
      5. Normalize pixels to 0.0 - 1.0
      6. Add batch dimension
    """
    img       = Image.open(image_path)
    img       = img.convert('RGB')
    img       = img.resize(IMG_SIZE)
    img_array = np.array(img)
    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)  # shape: (1, 224, 224, 3)
    return img_array


# ============================================================
# SECTION 4: API Routes
# ============================================================

@app.route('/', methods=['GET'])
def home():
    """
    Home route. Confirms server is running.
    Visit: http://localhost:5000
    """
    return jsonify({
        'project' : 'ChestXrayProject',
        'message' : 'Respiratory Disease Detection API is running.',
        'usage'   : 'POST an image to /predict to get a diagnosis.',
        'classes' : list(CLASS_DISPLAY_NAMES.values())
    })


@app.route('/health', methods=['GET'])
def health():
    """
    Health check route.
    Visit: http://localhost:5000/health
    """
    return jsonify({
        'project'     : 'ChestXrayProject',
        'status'      : 'running',
        'model_loaded': model is not None,
        'classes'     : CLASS_NAMES,
        'input_size'  : '224x224'
    })


@app.route('/predict', methods=['POST'])
def predict():
    """
    Prediction endpoint.
    Send a POST request with an image file (key: 'file').
    Returns predicted disease and confidence score.
    """

    # ---- Step 1: Check model is loaded ----------------------
    if model is None:
        return jsonify({
            'status' : 'error',
            'message': 'Model not loaded. Check server logs.'
        }), 500

    # ---- Step 2: Check file was sent ------------------------
    if 'file' not in request.files:
        return jsonify({
            'status' : 'error',
            'message': 'No file found. Send image with key name: file'
        }), 400

    file = request.files['file']

    # ---- Step 3: Check file is not empty --------------------
    if file.filename == '':
        return jsonify({
            'status' : 'error',
            'message': 'No file selected.'
        }), 400

    # ---- Step 4: Check file extension -----------------------
    if not allowed_file(file.filename):
        return jsonify({
            'status' : 'error',
            'message': 'File type not allowed.',
            'allowed': list(ALLOWED_EXTENSIONS)
        }), 400

    # ---- Step 5: Save file temporarily ----------------------
    saved_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
    file.save(saved_path)

    # ---- Step 6: Preprocess image ---------------------------
    try:
        img_array = preprocess_image(saved_path)
    except Exception as e:
        return jsonify({
            'status' : 'error',
            'message': f'Image processing failed. Reason: {str(e)}'
        }), 500

    # ---- Step 7: Run prediction -----------------------------
    try:
        predictions     = model.predict(img_array, verbose=0)
        predicted_index = int(np.argmax(predictions[0]))
        confidence      = float(predictions[0][predicted_index]) * 100
        predicted_class = CLASS_NAMES[predicted_index]
        disease_name    = CLASS_DISPLAY_NAMES[predicted_class]

        all_probs = {
            CLASS_DISPLAY_NAMES[CLASS_NAMES[i]]: round(float(predictions[0][i]) * 100, 2)
            for i in range(len(CLASS_NAMES))
        }

    except Exception as e:
        return jsonify({
            'status' : 'error',
            'message': f'Prediction failed. Reason: {str(e)}'
        }), 500

    # ---- Step 8: Delete temp file ---------------------------
    try:
        os.remove(saved_path)
    except Exception:
        pass

    # ---- Step 9: Return JSON result -------------------------
    return jsonify({
        'status'           : 'success',
        'predicted_class'  : predicted_class,
        'disease'          : disease_name,
        'confidence'       : round(confidence, 2),
        'all_probabilities': all_probs
    })


# ============================================================
# SECTION 5: Run the Server
# ============================================================

if __name__ == '__main__':
    print()
    print("=" * 55)
    print("  ChestXrayProject - Flask Backend")
    print("  Respiratory Disease Detection")
    print("=" * 55)
    print(f"  Upload folder : {UPLOAD_FOLDER}")
    print(f"  Model path    : {MODEL_PATH}")
    print(f"  Classes       : {len(CLASS_NAMES)} classes")
    print()
    print("  Server running at http://localhost:5000")
    print("  Press CTRL+C to stop.")
    print("=" * 55)
    print()

    app.run(
        host  = '0.0.0.0',
        port  = 5000,
        debug = True
    )