# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hHkwqKXr5sWai42q1bCdI6f7xHw9av3
"""

# ============================================================
# test_api.py - Test ChestXrayProject Flask Backend
# ============================================================
# Run this in a second terminal while app.py is running.
# Usage: python test_api.py

import os
import requests

BASE_URL = 'http://localhost:5000'

# ---- Test 1: Home -------------------------------------------
print("Test 1: Home route")
response = requests.get(f'{BASE_URL}/')
print(f"  Status   : {response.status_code}")
print(f"  Response : {response.json()}")
print()

# ---- Test 2: Health check -----------------------------------
print("Test 2: Health check")
response = requests.get(f'{BASE_URL}/health')
print(f"  Status   : {response.status_code}")
print(f"  Response : {response.json()}")
print()

# ---- Test 3: Predict ----------------------------------------
IMAGE_PATH = 'test_xray.jpg'

if not os.path.exists(IMAGE_PATH):
    print("Test 3: Prediction")
    print(f"  Skipped. Place a chest X-ray image named")
    print(f"  'test_xray.jpg' in ChestXrayProject/backend/")
    print(f"  then re-run this script.")
else:
    print("Test 3: Prediction")
    with open(IMAGE_PATH, 'rb') as img_file:
        response = requests.post(
            f'{BASE_URL}/predict',
            files={'file': img_file}
        )
    result = response.json()
    print(f"  Status     : {response.status_code}")
    print(f"  Disease    : {result.get('disease')}")
    print(f"  Confidence : {result.get('confidence')}%")
    print()
    print("  All probabilities:")
    for disease, prob in result.get('all_probabilities', {}).items():
        bar = '#' * int(prob / 5)
        print(f"    {disease:<20}  {prob:>6.2f}%  {bar}")